/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TournamentsIndexRouteImport } from './routes/tournaments.index'
import { Route as TeamsIndexRouteImport } from './routes/teams.index'
import { Route as TournamentsNewRouteImport } from './routes/tournaments.new'
import { Route as TeamsNewRouteImport } from './routes/teams.new'
import { Route as TeamsTeamIdRouteImport } from './routes/teams.$teamId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsIndexRoute = TournamentsIndexRouteImport.update({
  id: '/tournaments/',
  path: '/tournaments/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIndexRoute = TeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsNewRoute = TournamentsNewRouteImport.update({
  id: '/tournaments/new',
  path: '/tournaments/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsNewRoute = TeamsNewRouteImport.update({
  id: '/teams/new',
  path: '/teams/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdRoute = TeamsTeamIdRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/teams/new': typeof TeamsNewRoute
  '/tournaments/new': typeof TournamentsNewRoute
  '/teams/': typeof TeamsIndexRoute
  '/tournaments/': typeof TournamentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/teams/new': typeof TeamsNewRoute
  '/tournaments/new': typeof TournamentsNewRoute
  '/teams': typeof TeamsIndexRoute
  '/tournaments': typeof TournamentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/teams/new': typeof TeamsNewRoute
  '/tournaments/new': typeof TournamentsNewRoute
  '/teams/': typeof TeamsIndexRoute
  '/tournaments/': typeof TournamentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/teams/$teamId'
    | '/teams/new'
    | '/tournaments/new'
    | '/teams/'
    | '/tournaments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/teams/$teamId'
    | '/teams/new'
    | '/tournaments/new'
    | '/teams'
    | '/tournaments'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/teams/$teamId'
    | '/teams/new'
    | '/tournaments/new'
    | '/teams/'
    | '/tournaments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  TeamsTeamIdRoute: typeof TeamsTeamIdRoute
  TeamsNewRoute: typeof TeamsNewRoute
  TournamentsNewRoute: typeof TournamentsNewRoute
  TeamsIndexRoute: typeof TeamsIndexRoute
  TournamentsIndexRoute: typeof TournamentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/': {
      id: '/tournaments/'
      path: '/tournaments'
      fullPath: '/tournaments/'
      preLoaderRoute: typeof TournamentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/': {
      id: '/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof TeamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/new': {
      id: '/tournaments/new'
      path: '/tournaments/new'
      fullPath: '/tournaments/new'
      preLoaderRoute: typeof TournamentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/new': {
      id: '/teams/new'
      path: '/teams/new'
      fullPath: '/teams/new'
      preLoaderRoute: typeof TeamsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId': {
      id: '/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof TeamsTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  TeamsTeamIdRoute: TeamsTeamIdRoute,
  TeamsNewRoute: TeamsNewRoute,
  TournamentsNewRoute: TournamentsNewRoute,
  TeamsIndexRoute: TeamsIndexRoute,
  TournamentsIndexRoute: TournamentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
